services:
  - type: web
    name: house-ddx
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    autoDeploy: true